### ISSUE TITLE
USB Dongle not found

### ISSUE THREAD

**Issue by hreuver0183** [bdbcat/o-charts_pi#23]
The problem: with the old oesenc pluging the charts worked fine.
With the new plugin I can login, but I'm forced to give a system ID _and_ the USB dongle is not found.

Closing the system (arm64, native) and starting opencpn/flatpak a native  the USB dongle is visible and the charts work.
The sglock rule in udev did not change between stopping opencpn and starting flatpak,

Reason to want a native version of the plugin is because it is easier to work with unsupported (old) plugins.

USB dongle version 1.0.0.
The sglock rule in udev did not change between stopping opencpn and starting flatpak,
'$ /usr/local/bin/oeserverd -s
'1
'$ /usr/local/bin/oexserverd -s
'0
'$ .var/app/org.opencpn.OpenCPN/bin/oexserverd -s
'1

**Comment by hreuver0183** [comment]
To make the story complete:
'$ ./.var/app/org.opencpn.OpenCPN/bin/oexserverd -s
'1
'$ ./.local/bin/oexserverd -s 
'0
'$ cd ./.local/bin
'$ ./oexserverd -s
'1
'$ cd /usr/.local/bin
'$ ./oexserverd -s
'1

**Comment by hreuver0183** [comment]
I have tested a little further, but the above already contains the quick fix:
[o-charts-oexserverd.diff.txt](https://github.com/bdbcat/o-charts_pi/files/8165190/o-charts-oexserverd.diff.txt)

The problem seems to be the binary oexserverd only works in the ~/.local/app/org.opencpn.OpenCPN/bin location. And the fix forces the path to exactly that. A litte further there was also a second lookup for a binary in /usr/local/bin (which I removed). With the fix I get:
22:55:49.000 MESSAGE o-charts_pi.cpp:640 Path to oexserverd is: /home/opencpn/.local/bin/oexserverd
22:55:49.000 MESSAGE o-charts_pi.cpp:643 Path to oexserverd is: /home/opencpn/.var/app/org.opencpn.OpenCPN/bin/oexserverd
22:55:49.336 MESSAGE fpr.cpp:99 oexserverd results:
22:55:49.336 MESSAGE fpr.cpp:102 1
22:55:49.336 MESSAGE o-charts_pi.cpp:646 Dongle detected

Could you fix the oexserverd?

**Comment by bdbcat** [comment]
We are not today supporting o-charts on arm64 native builds.  Flatpak only, for that platform.
That said, will you describe again the change in oexserverd that you would like to see?
Thanks
Dave

**Comment by hreuver0183** [comment]
I think it is most clear when I refrase the 2nd message more verbose.

I first checked if the binary worked in /usr/local/bin (the old location of oeserverd when build as a deb-package).
This resulted in:
'$ /usr/local/bin/oexserverd -s
'0

Since flatpak worked I also tried the oexserver installed there:
'~/.var/app/org.opencpn.OpenCPN/bin/oexserverd -s
'1

And the directory where the tarball installer places the binary:
'~/.local/bin/oexserverd -s
'0

Since I thought it strange I tried some regression testing:
'$ diff ~/.var/app/org.opencpn.OpenCPN/bin/oexserverd  diff /usr/local/bin/oexserverd
'(same binary)
'$ cp ~/.var/app/org.opencpn.OpenCPN/bin/oexserverd  diff /usr/local/bin/oexserverd
'$ /usr/local/bin/oexserverd -s
'0
'$ cd /usr/local/bin
'$ ./oexserverd -s
'1

My conclusion, the binary uses some kind of fixed path, otherwise it doesn't work right.

If it is too hard the alternative way there would be an option  when used not with flatpak (the default being using the fixed path, the option to use the standard path). On x86_64 you should have the same problem with both native and flatpak ports being available.

**Comment by bdbcat** [comment]
oexserverd is designed to run from any directory.
Maybe a missing piece:
If dongle support is required, the associated platform specific SGLock library must be present in that directory.  For arm64 architecture, the library is "libsglarm64-2.31.0.0.so"

**Comment by hreuver0183** [comment]
I see we agree on what oexserverd should do.

And luckily it is easy to test:
'opencpn@arm64:$ ls -al /usr/local/bin/
'-rw-r--r-- 1 root root    38160 Feb 13 18:04 libsglarm64-2.31.0.0.so
'-rwxr-xr-x 1 root root    76648 Feb 13 18:04 oeserverd
'-rwxr-xr-x 1 root root   105648 Feb 28 20:11 oexserverd-old
'opencpn@arm64:$ oeserverd -s
'1
'opencpn@arm64:$ oexserverd-old -s
'opencpn@arm64:$ 0
'opencpn@arm64:$ cd /usr/local/bin/
'opencpn@arm64:/usr/local/bin$ oexserverd -s
'opencpn@arm64:/usr/local/bin$ 1
'opencpn@arm64:/usr/local/bin$ cd
'opencpn@arm64:~$ .var/app/org.opencpn.OpenCPN/bin/oexserverd -s
'opencpn@arm64:~$ 1
'opencpn@arm64:~$ ls -al .var/app/org.opencpn.OpenCPN/bin/
'drwxr-xr-x 2 opencpn opencpn   4096 Mar  1 04:56 .
'drwxr-xr-x 8 opencpn opencpn    4096 Mar  1 17:58 ..
'-rwxr-xr-x 1 opencpn opencpn 3366504 Jan  1  1970 ip
'-rw-r--r-- 1 opencpn opencpn   38160 Mar  1 04:56 libsglarm64-2.31.0.0.so
'-rwxr-xr-x 1 opencpn opencpn  105648 Mar  1 04:58 oexserverd
'opencpn@arm64:~$ cp -a .var/app/org.opencpn.OpenCPN/bin/ oex-bin
'opencpn@arm64:~$ ls -al oex-bin/
'total 3440
'drwxr-xr-x  2 opencpn opencpn    4096 Mar  1 04:56 .
'drwxr-x--- 30 opencpn opencpn    4096 Mar  2 18:15 ..
'-rwxr-xr-x  1 opencpn opencpn 3366504 Jan  1  1970 ip
'-rw-r--r--  1 opencpn opencpn   38160 Mar  1 04:56 libsglarm64-2.31.0.0.so
'-rwxr-xr-x  1 opencpn opencpn  105648 Mar  1 04:58 oexserverd
'opencpn@arm64:~$ oex-bin/oexserverd -s
'opencpn@arm64:~$ 0
'opencpn@arm64:~$ cd oex-bin/
'opencpn@arm64:~/oex-bin$ ./oexserverd -s 
'opencpn@arm64:~/oex-bin$ 1

I can only draw 2 conclusions:
- it does not meet the requirements I would like on arm64/aarch64.
- it behaves correctly on x86_64/ (all checks with 1 when the dongle is present).

**Comment by bdbcat** [comment]
1.  I don't know exactly what you would like.  Without more specifics here, I am unable to advise you.  Please tell me in simple words what you need, and I will see if it is possible to conform within in the current design. 

2.  I see two instances in the trace where it performs _as designed_.
opencpn@arm64:$ cp -a .var/app/org.opencpn.OpenCPN/bin/ oex-bin

opencpn@arm64:$ cd oex-bin/

opencpn@arm64:/oex-bin$ ./oexserverd -s
opencpn@arm64:/oex-bin$ 1

Conclusion:  Working _as designed_. oexserverd and libsgl...so must be in the current directory at runtime.

**Comment by hreuver0183** [comment]
Case 1:
opencpn@arm64:$ cd oex-bin/
opencpn@arm64:/oex-bin$ ./oexserverd -s
opencpn@arm64:/oex-bin$ 1

It is working, but that is not the way opencpn uses it.

Case 2:
opencpn@arm64:$ oex-bin/oexserverd -s
opencpn@arm64:$ 0

This is the way opencpn uses the check for the oexserverd.
Result: there is no USB dongle present, you have no charts available.

**Comment by bdbcat** [comment]
I understand what you say.
It all works just fine in flatpak.
I will do some tests in native arm64.
For me, in ubuntu/20.04, aarch64,  after installing flatpak OCPN, I can do this:

```
ubuntu@ubuntu:~$ .var/app/org.opencpn.OpenCPN/bin/oexserverd -s
ubuntu@ubuntu:~$ 1

```
I wonder why you cannot.

**Comment by hreuver0183** [comment]
I can do us much as that.
Only when you use the plugin native you get:

ubuntu@ubuntu:~$ .local/bin/oexserverd -s
ubuntu@ubuntu:~$ 0

On x86_64 this results in 1 and a working USB dongle.
That is exactly the problem.

**Comment by bdbcat** [comment]
That is very strange, since the oexserverd is exactly the same code, (flatpak and native) and the paths are not really so different.
I will think on this...

**Comment by hreuver0183** [comment]
The other way would be to formalize the above workaround.
But that would yield some super ugly code for a not-supported platform. I think we'd better not go that way.

**Comment by hreuver0183** [comment]
Last comment on this:
When I download the github sources, the included oexserverd works ( a patch with 'git' in it).
When I try the flatpak binary it works (a path with 'var' in it).
The standard location for the native plugin does not work.

Is there a trend?
Yes, any path less deep than 5 directories fails.

So the next locations work:
```
$ /home/opencpn/git/o-charts_pi/libs/oeserverd/linuxarm64/oexserverd -s
$ 1
$ /home/opencpn/.var/app/org.opencpn.OpenCPN/bin/oexserverd -s
$ 1
$ /home/opencpn/.local/opencpn/bin/oexserverd -s
$ 1
```

A shorter path fails.
