### ISSUE TITLE
error messages: void password

### ISSUE THREAD

**Issue by hreuver0183** [bdbcat/o-charts_pi#24]
Some error messages are unclear (or my english is not good enough).

When the system gives "void password" this translates to either "empty", "useless" or "undefined" in my opinion.
How can this matter arise?
Lack of internet connection?

If it happens when either password or name is not supplied I could guess, but when a password has been supplied?
Is it possible the password contains some illegal characters?

Is there a list of possible errors with a explanation what to look for?

**Comment by hreuver0183** [comment]
In the code of the plugin the error message is characterized as "3f, void password".
What I know is that it is not a wrong password and the user tries to give a password.

The message is still "void password". What is the logic here?

**Comment by bdbcat** [comment]
The message "3f, void password" is generated when the server replies with error code "3f".
It means just that the password field in the request to the serer is empty.
In what context are you seeing this message?
Have you tried to "Reset o-charts credentials" in o-charts_pi preferences?
