### ISSUE TITLE
RPi5 Dongle key not detected

### ISSUE THREAD

**Issue by Hakansv** [bdbcat/o-charts_pi#43]
o-charts is now available but the key dongle is not detected.
No extra actions are performed by me. I suppose o-charts are expected to trace it?

More info:..
rpi5@raspberrypi:/etc/udev $ lsusb
........
Bus 001 Device 003: ID 1547:1000 SG Intec Ltd & Co KG SG-Lock[U2]
........
rpi5@raspberrypi:/etc/udev $ ls
hwdb.d  rules.d  udev.conf
rpi5@raspberrypi:/etc/udev $ cd rules.d
rpi5@raspberrypi:/etc/udev/rules.d $ ls
99-com.rules

uname -a:
Linux raspberrypi 6.1.0-rpi7-rpi-2712 #1 SMP PREEMPT Debian 1:6.1.63-1+rpt1 (2023-11-24) aarch64 GNU/Linux

**Comment by bdbcat** [comment]
Is this Bookworm on RPi/5

**Comment by Hakansv** [comment]
Yes it is.

**Comment by bdbcat** [comment]
Hakan..
libusb installed?

$sudo apt install libusb-0.1-4

**Comment by Hakansv** [comment]
Dave..
No nothing extra performed. I thought O or o-charts should detect and either install liusb or inform the user to do so. But my  memory may fail? 
Any how.. after installation of libusb everything is fine. Very fast chart download and installation on this machine. :)

**Comment by bdbcat** [comment]
Using a managed plugin (in "user space"), it is not possible to install libraries that need "su".
I think it may be possible to pop up a message, if necessary.  Frankly, never thought of that.
I'll look into it.

**Comment by Hakansv** [comment]
So, my memory again..
Thanks.
